### ISSUE TITLE
Error events not being sent to onError callback

### ISSUE THREAD

**Issue by jifiti-omer** [Mastercard/connect-web-sdk#3]
Hello,

Error events that are not fatal errors, are not being sent to the onError event handler.
For example, when trying to login with:
username - demo
password - 123 (or any other passwords that generate an error),

An error is visible to the user, but the onError handler is not called.

Looking at the events being raised, we can see the following events:
![image](https://github.com/Mastercard/connect-web-sdk/assets/172589397/9a8984bb-c232-4a51-8c31-5fad59f5d611)

**Comment by alexsalido** [comment]
@jifiti-omer the `onError` event/callback will only be triggered if the user exits from an error screen. The user events shown in the screenshot are not fatal, the error is from our backend but is recoverable. You'll see a similar set of events if you trigger a 103 error which corresponds to invalid credentials. Try 
username: invalid_user 
password: go


A way to trigger the `onError` event is by allowing the session to expire and clicking the "exit" cta. You can also launch an expired Connect URL and exit from that error screen.

**Comment by jifiti-omer** [comment]
@alexsalido Thanks for the detailed response.
 For analytical reasons we would like to know every error the user had even if it is not fatal. 
 Theoretically,  we could listen to `CreateErrorAlert` events, but we would like to make sure this is not something that might change, as there is no documentation for it. In other words, is `CreateErrorAlert` part of the contract?

**Comment by alexsalido** [comment]
@jifiti-omer The `CreateErrorAlert` is now a deprecated event, please refer to this [documentation](https://developer.mastercard.com/open-banking-us/documentation/connect/connect-2-events/#user-events-optional), you'll find a list of all the currently supported user events. The `CreateErrorAlert` has been replaced by the `DisplayAlert` event.

**Comment by jifiti-omer** [comment]
@alexsalido Thanks a lot
